/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:04cc0e28-faf7-4d7c-98b9-d776be90c833",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_gfWsMxUVc",
    "aws_user_pools_web_client_id": "4o89lkoe9b24h0r81s2cjs88de",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://192.168.56.1:20002/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
