// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:767b9bc0-5163-4331-a0ef-ba2c25ee2c39",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_8QUMOH53Q",
    "aws_user_pools_web_client_id": "4on009jbg7ss6qk0o1td454rhi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://10.0.2.15:20002/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
